[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [
    ".git",
    "venv",
    "staticfiles",
    "__pycache__",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = [
    "B008",  # function calls in default arguments are common in Django settings/forms.
]

[tool.ruff.lint.per-file-ignores]
"interlinker/migrations/*" = ["E501"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "interlinker_tool.settings"
pythonpath = ["."]
