# Generated by Django 5.2.5 on 2025-10-27 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlinker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterlinkGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_excerpt', models.TextField()),
                ('linked_html', models.TextField()),
                ('inserted_total', models.PositiveSmallIntegerField(default=0)),
                ('inserted_priority', models.PositiveSmallIntegerField(default=0)),
                ('inserted_auto', models.PositiveSmallIntegerField(default=0)),
                ('max_links', models.PositiveSmallIntegerField(default=10)),
                ('source_is_html', models.BooleanField(default=False)),
                ('priority_pairs', models.JSONField(blank=True, default=list)),
                ('inserted_records', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interlink_generations', to='interlinker.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interlink_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
